### PR TITLE
fix compile failure on v141_xp c++17

### PR DESCRIPTION
**Pull request by HIllya51**
Explicitly declaring the referenced variables or removing the following constexpr ( [1](https://github.com/rapidfuzz/rapidfuzz-cpp/blob/main/rapidfuzz/distance/Levenshtein_impl.hpp#L730) [2](https://github.com/rapidfuzz/rapidfuzz-cpp/blob/main/rapidfuzz/distance/LCSseq_impl.hpp#L231) [3](https://github.com/rapidfuzz/rapidfuzz-cpp/blob/main/rapidfuzz/distance/LCSseq_impl.hpp#L245) ) can both result in successful compilation. Perhaps there are some bugs on the old compiler that I cannot understand
```
RAPIDFUZZ_IF_CONSTEXPR (RecordMatrix) {//replace RAPIDFUZZ_IF_CONSTEXPR as if can compile success
                    auto& res_ = getMatrixRef(res);
                   ......
```

details:

重新生成开始于 15:40...
1>------ 已启动全部重新生成: 项目: ConsoleApplication1, 配置: Release Win32 ------
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v150\Platforms\Win32\PlatformToolsets\v141_xp\Toolset.targets(39,5): warning MSB8051: 面向 Windows XP 的支持已被弃用，将来的 Visual Studio 版本不再提供该支持。请访问 https://go.microsoft.com/fwlink/?linkid=2023588，获取详细信息。
1>FileName.cpp
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(731): error C2065: “res”: 未声明的标识符
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(888): note: 参见对正在编译的函数 模板 实例化“rapidfuzz::detail::LevenshteinResult<false,false> rapidfuzz::detail::levenshtein_hyrroe2003_block<false,false,std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::BlockPatternMatchVector &,const rapidfuzz::detail::Range<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>> &,const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,size_t,size_t)”的引用
1>        with
1>        [
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein.hpp(458): note: 参见对正在编译的函数 模板 实例化“size_t rapidfuzz::detail::uniform_levenshtein_distance<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::BlockPatternMatchVector &,rapidfuzz::detail::Range<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>>,rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>,size_t,size_t)”的引用
1>        with
1>        [
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(249): note: 参见对正在编译的函数 模板 实例化“size_t rapidfuzz::CachedLevenshtein<wchar_t>::_distance<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,size_t,size_t) const”的引用
1>        with
1>        [
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(249): note: 参见对正在编译的函数 模板 实例化“size_t rapidfuzz::CachedLevenshtein<wchar_t>::_distance<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,size_t,size_t) const”的引用
1>        with
1>        [
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(259): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::_normalized_distance<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(259): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::_normalized_distance<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(236): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::_normalized_similarity<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\details\distance.hpp(236): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::_normalized_similarity<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>>(const rapidfuzz::detail::Range<std::_String_const_iterator<std::_String_val<std::_Simple_types<_Ty>>>> &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            _Ty=wchar_t
1>        ]
1>c:\users\11737\source\repos\consoleapplication1\filename.cpp(17): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::normalized_similarity<Sentence2>(const Sentence2 &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            Sentence2=std::wstring
1>        ]
1>c:\users\11737\source\repos\consoleapplication1\filename.cpp(17): note: 参见对正在编译的函数 模板 实例化“double rapidfuzz::detail::CachedNormalizedMetricBase<T>::normalized_similarity<Sentence2>(const Sentence2 &,double,double) const”的引用
1>        with
1>        [
1>            T=rapidfuzz::CachedLevenshtein<wchar_t>,
1>            Sentence2=std::wstring
1>        ]
1>c:\users\11737\source\repos\consoleapplication1\filename.cpp(26): note: 参见对正在编译的函数 模板 实例化“double levenshtein_normalized_similarity<std::wstring,std::wstring>(const Sentence1 &,const Sentence2 &,rapidfuzz::LevenshteinWeightTable,double)”的引用
1>        with
1>        [
1>            Sentence1=std::wstring,
1>            Sentence2=std::wstring
1>        ]
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(731): error C2530: “res_”: 必须初始化引用
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(732): error C3536: “res_”: 初始化之前无法使用
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(732): error C2065: “row”: 未声明的标识符
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(732): error C2065: “first_block”: 未声明的标识符
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(733): error C2065: “row”: 未声明的标识符
1>c:\users\11737\documents\github\rapidfuzz-cpp\rapidfuzz\distance\levenshtein_impl.hpp(733): error C2065: “first_block”: 未声明的标识符
1>已完成生成项目“ConsoleApplication1.vcxproj”的操作 - 失败。
========== “全部重新生成”: 0 成功，1 失败，0已跳过 ==========
========== 重新生成 于 15:40 完成，耗时 01.210 秒 ==========

### CODE REVIEW

**Comment by maxbachmann** [comment]
This sounds like a compiler bug. Apparently MSVC had issues with if constexpr inside lambdas:
- https://developercommunity.visualstudio.com/t/compiler-does-not-adhere-to-c-standard-for-if-cons/140295
- https://developercommunity.visualstudio.com/t/msvc-does-not-respect-constexpr-if-within-lambdas/229226

Testing on godbolt shows this to be working in msvc 19.20 and broken in msvc 19.10 (https://godbolt.org/z/a793hvGfP). Unfortunately they don't provide any intermediate versions that I could test with. Since we don't necessarily need to use it there I would just consider it broken up until msvc 19.20 unless you are able to test on different versions.

```
#if ((defined(_MSVC_LANG) && _MSVC_LANG >= 201703L) || __cplusplus >= 201703L)
#    define RAPIDFUZZ_DEDUCTION_GUIDES
#    define RAPIDFUZZ_IF_CONSTEXPR_AVAILABLE 1
#    define RAPIDFUZZ_IF_CONSTEXPR if constexpr
#else
#    define RAPIDFUZZ_IF_CONSTEXPR_AVAILABLE 0
#    define RAPIDFUZZ_IF_CONSTEXPR if
#endif
```
should be updated to check the msvc version as well.

**Comment by HIllya51** [comment]
I'm using 19.16.27051.
This is the last MSVC version that supports Windows XP, so it is a very special version that many people use it and cannot upgrade.
And I think it's not necessary modify this macro, as it would compromise performance. Just explicitly declare the captured references like in this PR can avoid compilation errors without slowing down program.

**Comment by maxbachmann** [comment]
The only reason for the `if constexpr` is that it accesses variables that are unavailable and so the pre C++17 version requires some ugly hacks using `reinterpret_cast`. This doesn't affect the performance in any way. The branch will be dropped in both cases since it's based on compile time known values.

So really this is just a "cleaner" way of doing this and we should just drop it on compilers that fail to implement it properly.

**Comment by HIllya51** [comment]
ok ❤

**Comment by maxbachmann** [comment]
@HIllya51 I published a new version that should fix this issue for you

**Comment by HIllya51** [comment]
thanks，it work fine



---Original---
From: "Max ***@***.***&gt;
Date: Tue, Feb 11, 2025 20:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rapidfuzz/rapidfuzz-cpp] fix compile failure on v141_xp c++17(PR #121)




 
@HIllya51 I published a new version that should fix this issue for you
